In [1]:
# Para trabajar con regex
# -----------------------------------------------------------------------
import re

# Para trabajar con ficheros
# -----------------------------------------------------------------------
import os


# Para trabajar con los DataFrames
# -----------------------------------------------------------------------
import pandas as pd

# Para poner barras progreso
# -----------------------------------------------------------------------
from tqdm import tqdm



# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

# Ignorar warings
# -----------------------------------------------------------------------
import warnings
warnings.filterwarnings("ignore")

# Librerias para generar gráficas
# ----------------------------------------------------------------------
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df_tasa_repetidores_primaria=pd.read_csv("datos/ministerio-educacion/tasa_alumnado_repetidor_primaria.csv", encoding= 'latin-1', sep=';')

In [7]:
df_tasa_repetidores_primaria.sample(20)

,Titularidad,Sexo,Comunidad autónoma/provincia,Curso,Total
1264,TODOS LOS CENTROS,Mujeres,"14 MURCIA, REGIÓN DE",Cuarto,"4,4"
3848,CENTROS PRIVADOS,Mujeres,11 EXTREMADURA,Quinto,"1,3"
1178,TODOS LOS CENTROS,Mujeres,Alicante/Alacant,Segundo,"2,1"
708,TODOS LOS CENTROS,Hombres,Girona,Primero,"0,6"
3582,CENTROS PRIVADOS,Mujeres,Jaén,Quinto,"0,8"
2899,CENTROS PRIVADOS,AMBOS SEXOS,09 CATALUÑA,Primero,"0,5"
3709,CENTROS PRIVADOS,Mujeres,Salamanca,Sexto,"2,4"
2322,CENTROS PÚBLICOS,Mujeres,05 CANARIAS,Quinto,"0,9"
449,TODOS LOS CENTROS,Hombres,01 ANDALUCÍA,Primero,"3,4"
1660,CENTROS PÚBLICOS,AMBOS SEXOS,12 GALICIA,Primero,"2,6"
3084,CENTROS PRIVADOS,AMBOS SEXOS,19 MELILLA,Cuarto,"1,8"
3609,CENTROS PRIVADOS,Mujeres,Huesca,Cuarto,"1,6"
3178,CENTROS PRIVADOS,Hombres,Zaragoza,Total,"2,2"
2689,CENTROS PRIVADOS,AMBOS SEXOS,Huelva,Primero,"1,7"
3019,CENTROS PRIVADOS,AMBOS SEXOS,"13 MADRID, COMUNIDAD DE",Segundo,"1,4"
2647,CENTROS PRIVADOS,AMBOS SEXOS,00 TOTAL,Primero,"1,1"
3340,CENTROS PRIVADOS,Hombres,09 CATALUÑA,Primero,"0,7"
591,TODOS LOS CENTROS,Hombres,Ávila,Tercero,"4,1"
817,TODOS LOS CENTROS,Hombres,"13 MADRID, COMUNIDAD DE",Quinto,"2,5"
1365,CENTROS PÚBLICOS,AMBOS SEXOS,Huelva,Total,"3,0"

In [11]:
df_tasa_repetidores_secundaria=pd.read_csv("datos/ministerio-educacion/tasa_alumnado_repetidor_secundaria.csv", sep=';')

In [12]:
df_tasa_repetidores_secundaria.sample(20)

,Titularidad,Sexo,Comunidad autónoma/provincia,Curso,Total
396,TODOS LOS CENTROS,Hombres,05 CANARIAS,Primero,"9,2"
1161,CENTROS PÚBLICOS,AMBOS SEXOS,Castellón/Castelló,Primero,"10,1"
74,TODOS LOS CENTROS,AMBOS SEXOS,"03 ASTURIAS, PRINCIPADO DE",Cuarto,"4,8"
372,TODOS LOS CENTROS,Hombres,Huesca,Segundo,"8,7"
862,TODOS LOS CENTROS,Mujeres,Badajoz,Segundo,"6,9"
2657,CENTROS PRIVADOS,Mujeres,Soria,Segundo,"1,2"
1759,CENTROS PÚBLICOS,Mujeres,09 CATALUÑA,Cuarto,"3,5"
2158,CENTROS PRIVADOS,AMBOS SEXOS,"13 MADRID, COMUNIDAD DE",Tercero,"5,6"
1890,CENTROS PRIVADOS,AMBOS SEXOS,00 TOTAL,Total,"4,3"
283,TODOS LOS CENTROS,AMBOS SEXOS,16 PAÍS VASCO,Tercero,"5,2"
1672,CENTROS PÚBLICOS,Mujeres,06 CANTABRIA,Segundo,"6,4"
1382,CENTROS PÚBLICOS,Hombres,Palencia,Segundo,"10,4"
2548,CENTROS PRIVADOS,Mujeres,Granada,Tercero,"5,6"
845,TODOS LOS CENTROS,Mujeres,Castellón/Castelló,Total,"7,1"
174,TODOS LOS CENTROS,AMBOS SEXOS,Guadalajara,Cuarto,"9,8"
2534,CENTROS PRIVADOS,Mujeres,Almería,Cuarto,"3,2"
2760,CENTROS PRIVADOS,Mujeres,12 GALICIA,Total,"4,0"
2047,CENTROS PRIVADOS,AMBOS SEXOS,Albacete,Segundo,"9,0"
2207,CENTROS PRIVADOS,Hombres,00 TOTAL,Segundo,"5,6"
541,TODOS LOS CENTROS,Hombres,11 EXTREMADURA,Primero,"8,6"

In [13]:
df_tasa_repetidores_bachillerato=pd.read_csv("datos/ministerio-educacion/tasa_alumnado_repetidor_bachillerato.csv", sep=';')

In [14]:
df_tasa_repetidores_bachillerato.sample(20)

,Titularidad,Sexo,Comunidad autónoma/provincia,Curso,Total
943,CENTROS PÚBLICOS,Hombres,19 MELILLA,Primer Curso,"10,2"
481,TODOS LOS CENTROS,Mujeres,Guadalajara,Primer Curso,"6,8"
1069,CENTROS PÚBLICOS,Mujeres,10 COMUNITAT VALENCIANA,Primer Curso,"4,6"
286,TODOS LOS CENTROS,Hombres,Ciudad Real,Primer Curso,"5,2"
1216,CENTROS PRIVADOS,AMBOS SEXOS,Soria,Primer Curso,"0,0"
998,CENTROS PÚBLICOS,Mujeres,Las Palmas,Segundo Curso,"5,0"
1334,CENTROS PRIVADOS,Hombres,Cádiz,Segundo Curso,"6,8"
1683,CENTROS PRIVADOS,Mujeres,Araba/Álava,TODOS LOS CURSOS,"4,5"
644,CENTROS PÚBLICOS,AMBOS SEXOS,Salamanca,Segundo Curso,"18,2"
893,CENTROS PÚBLICOS,Hombres,11 EXTREMADURA,Segundo Curso,"13,4"
1518,CENTROS PRIVADOS,Mujeres,Almería,TODOS LOS CURSOS,"0,8"
170,TODOS LOS CENTROS,AMBOS SEXOS,16 PAÍS VASCO,Segundo Curso,"4,9"
134,TODOS LOS CENTROS,AMBOS SEXOS,Valencia/València,Segundo Curso,"4,2"
1181,CENTROS PRIVADOS,AMBOS SEXOS,"04 BALEARS, ILLES",Segundo Curso,"9,1"
1013,CENTROS PÚBLICOS,Mujeres,Burgos,Segundo Curso,"9,7"
1081,CENTROS PÚBLICOS,Mujeres,11 EXTREMADURA,Primer Curso,"5,5"
1083,CENTROS PÚBLICOS,Mujeres,Badajoz,TODOS LOS CURSOS,"7,7"
815,CENTROS PÚBLICOS,Hombres,06 CANTABRIA,Segundo Curso,"11,4"
977,CENTROS PÚBLICOS,Mujeres,02 ARAGÓN,Segundo Curso,"7,7"
1381,CENTROS PRIVADOS,Hombres,06 CANTABRIA,Primer Curso,"3,0"